"""Dry-run ONLY script for Live Observation Config Bootstrap (plan rev. 2).

GUARANTEES (hard-coded, not configurable):
  - NEVER calls commit() on the live DB.
  - The only mutation candidate is a single INSERT into
    ``execution_observation_config``, and it is performed inside an
    explicit transaction that is ALWAYS rolled back before the function
    returns, regardless of success/failure.
  - No other table is written to.
  - No seed / bootstrap / publish invoked.

Outputs (proof artifacts, written under /workspace/docs/proof):
  - live_observation_bootstrap_before.json   (identity + rows_before)
  - live_observation_bootstrap_dry_run.json  (full structured proof)
  - live_observation_bootstrap_dry_run.sql   (exact SQL intended + run)

Verdicts emitted via stdout and recorded inside dry_run.json:
  - DRY_RUN_READY_FOR_USER_REVIEW
  - BLOCKED_BY_PLATFORM_DEPLOY_STATE
  - SCHEMA_MISMATCH

LIVE_GUARD (runtime hygiene sprint, 2026-05-04):
  To prevent accidental execution against the live runtime, this script
  REFUSES to run unless ``DRY_RUN_ALLOWED_ON_LIVE=1`` is explicitly set
  in the environment. The guard is applied at ``__main__`` entry, so
  tests that import structural symbols are unaffected.

  To run intentionally (from an operator-approved shell only):
      DRY_RUN_ALLOWED_ON_LIVE=1 python scripts/dry_run_observation_bootstrap.py
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# LIVE_GUARD — block accidental execution against live runtime.
# Tests and importers can still reference module-level symbols.
# The guard only fires when this file is executed directly as a script.
# ---------------------------------------------------------------------------
_LIVE_GUARD_ENV = "DRY_RUN_ALLOWED_ON_LIVE"


def _enforce_live_guard() -> None:
    """Abort the process unless the operator explicitly opted in.

    Called only from the ``__main__`` path. Importing this module does
    not trigger the guard; this keeps static analysis and testing safe.
    """
    if os.environ.get(_LIVE_GUARD_ENV) != "1":
        sys.stderr.write(
            "[dry_run_observation_bootstrap] BLOCKED: live-guard active.\n"
            f"Set {_LIVE_GUARD_ENV}=1 to acknowledge the live-runtime risk and run.\n"
        )
        sys.exit(2)

# Ensure backend package imports resolve
_BACKEND_DIR = Path(__file__).resolve().parents[1]
if str(_BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(_BACKEND_DIR))

from sqlalchemy import text  # noqa: E402

from core.database import db_manager  # noqa: E402


PROOF_DIR = Path("/workspace/docs/proof")
BEFORE_PATH = PROOF_DIR / "live_observation_bootstrap_before.json"
DRY_RUN_JSON_PATH = PROOF_DIR / "live_observation_bootstrap_dry_run.json"
DRY_RUN_SQL_PATH = PROOF_DIR / "live_observation_bootstrap_dry_run.sql"


CANONICAL_VALUES = {
    "warning_time_delta_pct": 10,
    "critical_time_delta_pct": 20,
    "warning_time_delta_minutes": 15,
    "critical_time_delta_minutes": 30,
}

# Exact SQL we intend to run — persisted verbatim to dry_run.sql for audit.
SQL_TRACE_HEADER = """-- live_observation_bootstrap_dry_run.sql
-- Generated by scripts/dry_run_observation_bootstrap.py
-- Plan: docs/plans/plan__live_observation_config_bootstrap.md (revision 2)
-- MODE: DRY-RUN ONLY. No COMMIT. All mutations rolled back.
"""


def _utcnow_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, default=str) + "\n", encoding="utf-8")


def _write_sql_trace(path: Path, sections: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = SQL_TRACE_HEADER + "\n" + "\n".join(sections) + "\n"
    path.write_text(body, encoding="utf-8")


async def _step_identity(conn) -> dict[str, Any]:
    row = (await conn.execute(text(
        "SELECT current_database() AS db_name, "
        "inet_server_addr()::text AS server_addr, "
        "inet_server_port() AS server_port, "
        "current_user AS db_user, "
        "now()::text AS server_now"
    ))).mappings().first()
    return dict(row) if row else {}


async def _step_order_14(conn) -> dict[str, Any]:
    try:
        row = (await conn.execute(text(
            "SELECT id FROM orders WHERE id = 14"
        ))).mappings().first()
        return {"orders_table_present": True, "order_14_present": bool(row)}
    except Exception as exc:  # table may not exist
        return {
            "orders_table_present": False,
            "order_14_present": False,
            "error": f"{type(exc).__name__}: {exc}",
        }


async def _step_schema(conn) -> dict[str, Any]:
    """Confirm target table existence + shape + constraints."""
    regclass_row = (await conn.execute(text(
        "SELECT to_regclass('public.execution_observation_config')::text AS oid"
    ))).mappings().first()
    regclass_oid = regclass_row["oid"] if regclass_row else None

    if regclass_oid is None:
        return {
            "regclass_oid": None,
            "schema_confirmed": False,
            "columns": [],
            "constraints": [],
            "reason": "to_regclass returned NULL — table missing on live DB",
        }

    cols_rows = (await conn.execute(text(
        "SELECT column_name, data_type, is_nullable, column_default "
        "FROM information_schema.columns "
        "WHERE table_schema='public' AND table_name='execution_observation_config' "
        "ORDER BY ordinal_position"
    ))).mappings().all()
    columns = [dict(r) for r in cols_rows]

    cons_rows = (await conn.execute(text(
        "SELECT conname, contype::text AS contype, "
        "pg_get_constraintdef(oid) AS def "
        "FROM pg_constraint "
        "WHERE conrelid = 'public.execution_observation_config'::regclass"
    ))).mappings().all()
    constraints = [dict(r) for r in cons_rows]

    required = {
        "id",
        "warning_time_delta_pct",
        "critical_time_delta_pct",
        "warning_time_delta_minutes",
        "critical_time_delta_minutes",
    }
    col_names = {c["column_name"] for c in columns}
    schema_confirmed = required.issubset(col_names)

    return {
        "regclass_oid": regclass_oid,
        "schema_confirmed": schema_confirmed,
        "columns": columns,
        "constraints": constraints,
        "missing_required_columns": sorted(required - col_names),
    }


async def _step_count(conn) -> int:
    row = (await conn.execute(text(
        "SELECT COUNT(*)::int AS c FROM execution_observation_config"
    ))).mappings().first()
    return int(row["c"]) if row else 0


async def _step_dry_run_tx(engine, schema_info: dict[str, Any]) -> dict[str, Any]:
    """Open a transaction, perform a guarded INSERT, readback, ROLLBACK."""
    result: dict[str, Any] = {
        "tx_started": False,
        "inserted_candidate_id": None,
        "rows_in_transaction": None,
        "readback_last_rows": [],
        "rollback_confirmed": False,
        "error": None,
    }

    # Build INSERT column list. If table has additional NOT NULL columns
    # without defaults, we CANNOT dry-run safely; bail out.
    cols = {c["column_name"]: c for c in schema_info["columns"]}
    canonical_cols = list(CANONICAL_VALUES.keys())

    missing_defaults = []
    for name, info in cols.items():
        if name in canonical_cols or name == "id":
            continue
        if info["is_nullable"] == "NO" and info["column_default"] is None:
            # Created/updated timestamps auto-managed are usually not-null
            # with default now(); those have column_default set, so they
            # are safe. Anything else not-null without default blocks us.
            missing_defaults.append(name)

    if missing_defaults:
        result["error"] = (
            "extra_not_null_columns_without_defaults: "
            + ",".join(missing_defaults)
        )
        return result

    insert_sql = text(
        "INSERT INTO execution_observation_config "
        "(warning_time_delta_pct, critical_time_delta_pct, "
        " warning_time_delta_minutes, critical_time_delta_minutes) "
        "VALUES (:w_pct, :c_pct, :w_min, :c_min) RETURNING id"
    )

    async with engine.connect() as conn:
        trans = await conn.begin()
        result["tx_started"] = True
        try:
            ins = await conn.execute(insert_sql, {
                "w_pct": CANONICAL_VALUES["warning_time_delta_pct"],
                "c_pct": CANONICAL_VALUES["critical_time_delta_pct"],
                "w_min": CANONICAL_VALUES["warning_time_delta_minutes"],
                "c_min": CANONICAL_VALUES["critical_time_delta_minutes"],
            })
            inserted_id_row = ins.mappings().first()
            result["inserted_candidate_id"] = (
                int(inserted_id_row["id"]) if inserted_id_row else None
            )

            cnt_row = (await conn.execute(text(
                "SELECT COUNT(*)::int AS c FROM execution_observation_config"
            ))).mappings().first()
            result["rows_in_transaction"] = (
                int(cnt_row["c"]) if cnt_row else None
            )

            rb_rows = (await conn.execute(text(
                "SELECT * FROM execution_observation_config "
                "ORDER BY id DESC LIMIT 5"
            ))).mappings().all()
            result["readback_last_rows"] = [dict(r) for r in rb_rows]
        except Exception as exc:
            result["error"] = f"{type(exc).__name__}: {exc}"
        finally:
            # ALWAYS rollback — never commit in dry-run.
            await trans.rollback()
            result["rollback_confirmed"] = True

    return result


async def main() -> int:
    started_at = _utcnow_iso()
    PROOF_DIR.mkdir(parents=True, exist_ok=True)

    sql_sections: list[str] = []

    proof: dict[str, Any] = {
        "timestamp_utc": started_at,
        "mode": "dry_run_only",
        "plan": "docs/plans/plan__live_observation_config_bootstrap.md (revision 2)",
        "db_identity": {},
        "identity_confirmed": False,
        "orders_check": {},
        "schema_confirmed": False,
        "schema_details": {},
        "rows_before": None,
        "tx": {},
        "rows_after_rollback": None,
        "rollback_confirmed": False,
        "inserted_candidate_id": None,
        "rows_in_transaction": None,
        "readback_last_rows": [],
        "constraints": [],
        "columns": [],
        "blocked_condition": None,
        "verdict": None,
        "errors": [],
    }

    # ------------------------------------------------------------------
    # Connect to live DB
    # ------------------------------------------------------------------
    try:
        await db_manager.init_db()
        engine = db_manager.engine
        if engine is None:
            raise RuntimeError("db_manager.engine is None after init_db()")
    except Exception as exc:
        proof["errors"].append(f"engine_init_failed: {type(exc).__name__}: {exc}")
        proof["blocked_condition"] = "BLOCKED_BY_PLATFORM_DEPLOY_STATE"
        proof["verdict"] = "BLOCKED_BY_PLATFORM_DEPLOY_STATE"
        _write_json(DRY_RUN_JSON_PATH, proof)
        _write_json(BEFORE_PATH, {
            "timestamp_utc": started_at,
            "db_identity": {},
            "identity_confirmed": False,
            "order_14_present": False,
            "rows_before": None,
            "blocked_condition": "BLOCKED_BY_PLATFORM_DEPLOY_STATE",
        })
        _write_sql_trace(DRY_RUN_SQL_PATH, ["-- engine init failed; no SQL executed"])
        print(json.dumps({"verdict": proof["verdict"]}))
        return 2

    # ------------------------------------------------------------------
    # Step A — identity
    # ------------------------------------------------------------------
    identity_sql = (
        "-- Step A1: identity\n"
        "SELECT current_database() AS db_name, "
        "inet_server_addr()::text AS server_addr, "
        "inet_server_port() AS server_port, "
        "current_user AS db_user, now()::text AS server_now;"
    )
    sql_sections.append(identity_sql)

    try:
        async with engine.connect() as conn:
            identity = await _step_identity(conn)
            orders = await _step_order_14(conn)
    except Exception as exc:
        proof["errors"].append(f"identity_query_failed: {type(exc).__name__}: {exc}")
        proof["blocked_condition"] = "BLOCKED_BY_PLATFORM_DEPLOY_STATE"
        proof["verdict"] = "BLOCKED_BY_PLATFORM_DEPLOY_STATE"
        _write_json(DRY_RUN_JSON_PATH, proof)
        _write_json(BEFORE_PATH, {
            "timestamp_utc": started_at,
            "db_identity": {},
            "identity_confirmed": False,
            "order_14_present": False,
            "rows_before": None,
            "blocked_condition": "BLOCKED_BY_PLATFORM_DEPLOY_STATE",
            "errors": proof["errors"],
        })
        _write_sql_trace(DRY_RUN_SQL_PATH, sql_sections)
        print(json.dumps({"verdict": proof["verdict"]}))
        await engine.dispose()
        return 2

    proof["db_identity"] = identity
    proof["orders_check"] = orders
    proof["identity_confirmed"] = bool(identity.get("db_name")) and bool(
        identity.get("db_user")
    )

    sql_sections.append(
        "-- Step A2: orders anchor\nSELECT id FROM orders WHERE id = 14;"
    )

    # ------------------------------------------------------------------
    # Step B — schema
    # ------------------------------------------------------------------
    sql_sections.append(
        "-- Step B1: target existence\n"
        "SELECT to_regclass('public.execution_observation_config');"
    )
    sql_sections.append(
        "-- Step B2: columns\n"
        "SELECT column_name, data_type, is_nullable, column_default "
        "FROM information_schema.columns "
        "WHERE table_schema='public' AND table_name='execution_observation_config' "
        "ORDER BY ordinal_position;"
    )
    sql_sections.append(
        "-- Step B3: constraints\n"
        "SELECT conname, contype, pg_get_constraintdef(oid) "
        "FROM pg_constraint "
        "WHERE conrelid = 'public.execution_observation_config'::regclass;"
    )

    async with engine.connect() as conn:
        schema_info = await _step_schema(conn)

    proof["schema_confirmed"] = bool(schema_info["schema_confirmed"])
    proof["schema_details"] = schema_info
    proof["columns"] = schema_info.get("columns", [])
    proof["constraints"] = schema_info.get("constraints", [])

    if schema_info.get("regclass_oid") is None or not schema_info["schema_confirmed"]:
        proof["blocked_condition"] = "SCHEMA_MISMATCH"
        proof["verdict"] = "SCHEMA_MISMATCH"
        _write_json(DRY_RUN_JSON_PATH, proof)
        _write_json(BEFORE_PATH, {
            "timestamp_utc": started_at,
            "db_identity": identity,
            "identity_confirmed": proof["identity_confirmed"],
            "order_14_present": orders.get("order_14_present", False),
            "rows_before": None,
            "blocked_condition": "SCHEMA_MISMATCH",
            "schema_details": schema_info,
        })
        _write_sql_trace(DRY_RUN_SQL_PATH, sql_sections)
        print(json.dumps({"verdict": proof["verdict"]}))
        await engine.dispose()
        return 3

    # ------------------------------------------------------------------
    # Step C — count BEFORE
    # ------------------------------------------------------------------
    sql_sections.append(
        "-- Step C: count BEFORE\n"
        "SELECT COUNT(*) FROM execution_observation_config;"
    )
    async with engine.connect() as conn:
        rows_before = await _step_count(conn)
    proof["rows_before"] = rows_before

    # Emit BEFORE proof now so it is written even if the dry-run fails next.
    _write_json(BEFORE_PATH, {
        "timestamp_utc": started_at,
        "db_identity": identity,
        "identity_confirmed": proof["identity_confirmed"],
        "orders_check": orders,
        "order_14_present": orders.get("order_14_present", False),
        "rows_before": rows_before,
        "schema_confirmed": proof["schema_confirmed"],
        "schema_details": schema_info,
        "blocked_condition": None,
    })

    # ------------------------------------------------------------------
    # Step D — dry-run transaction (ALWAYS rolled back)
    # ------------------------------------------------------------------
    sql_sections.append(
        "-- Step D: dry-run transaction (ROLLBACK mandatory)\n"
        "BEGIN;\n"
        "INSERT INTO execution_observation_config (\n"
        "  warning_time_delta_pct, critical_time_delta_pct,\n"
        "  warning_time_delta_minutes, critical_time_delta_minutes\n"
        ") VALUES (10, 20, 15, 30) RETURNING id;\n"
        "SELECT COUNT(*) FROM execution_observation_config;\n"
        "SELECT * FROM execution_observation_config ORDER BY id DESC LIMIT 5;\n"
        "ROLLBACK;"
    )

    tx_result = await _step_dry_run_tx(engine, schema_info)
    proof["tx"] = tx_result
    proof["inserted_candidate_id"] = tx_result.get("inserted_candidate_id")
    proof["rows_in_transaction"] = tx_result.get("rows_in_transaction")
    proof["readback_last_rows"] = tx_result.get("readback_last_rows", [])
    proof["rollback_confirmed"] = bool(tx_result.get("rollback_confirmed"))

    # ------------------------------------------------------------------
    # Step E — confirm rollback (count after must equal rows_before)
    # ------------------------------------------------------------------
    sql_sections.append(
        "-- Step E: count AFTER rollback (must equal rows_before)\n"
        "SELECT COUNT(*) FROM execution_observation_config;"
    )
    async with engine.connect() as conn:
        rows_after_rollback = await _step_count(conn)
    proof["rows_after_rollback"] = rows_after_rollback

    # ------------------------------------------------------------------
    # Verdict
    # ------------------------------------------------------------------
    tx_error = tx_result.get("error")
    rollback_ok = (
        proof["rollback_confirmed"]
        and rows_after_rollback == rows_before
    )

    if tx_error:
        proof["errors"].append(f"tx_error: {tx_error}")

    if rollback_ok and tx_error is None:
        proof["verdict"] = "DRY_RUN_READY_FOR_USER_REVIEW"
    elif not rollback_ok:
        proof["blocked_condition"] = "ROLLBACK_UNCONFIRMED"
        proof["verdict"] = "BLOCKED_BY_PLATFORM_DEPLOY_STATE"
    else:
        proof["blocked_condition"] = "DRY_RUN_FAILED"
        proof["verdict"] = "BLOCKED_BY_PLATFORM_DEPLOY_STATE"

    _write_json(DRY_RUN_JSON_PATH, proof)
    _write_sql_trace(DRY_RUN_SQL_PATH, sql_sections)

    await engine.dispose()
    print(json.dumps({
        "verdict": proof["verdict"],
        "rows_before": rows_before,
        "rows_in_transaction": proof["rows_in_transaction"],
        "inserted_candidate_id": proof["inserted_candidate_id"],
        "rows_after_rollback": rows_after_rollback,
        "rollback_confirmed": proof["rollback_confirmed"],
        "schema_confirmed": proof["schema_confirmed"],
        "identity_confirmed": proof["identity_confirmed"],
    }))
    return 0


if __name__ == "__main__":
    _enforce_live_guard()
    sys.exit(asyncio.run(main()))