"""auto update

Revision ID: 1588bf4744d8
Revises: 6da9e3a96f3d
Create Date: 2026-04-28 08:22:43.988158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1588bf4744d8'
down_revision: Union[str, Sequence[str], None] = '6da9e3a96f3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_code', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('components_json', sa.String(), nullable=True),
    sa.Column('operations_json', sa.String(), nullable=True),
    sa.Column('required_materials_json', sa.String(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('base_labor_rate', sa.Float(), nullable=True),
    sa.Column('base_margin_pct', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_templates_id'), 'product_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_templates_id'), table_name='product_templates')
    op.drop_table('product_templates')
    # ### end Alembic commands ###