"""Add materials_json to ExecutionReality

Revision ID: 77f253fbb300
Revises: s22_materials_capture
Create Date: 2026-05-12 09:10:24.221916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f253fbb300'
down_revision: Union[str, Sequence[str], None] = 's22_materials_capture'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_engine_config', schema=None) as batch_op:
        batch_op.alter_column('moneda_implicita',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('overhead_profile_name',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('metoda_overhead',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('allow_manual_override',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('employee_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('execution_observation_config', schema=None) as batch_op:
        batch_op.alter_column('warning_time_delta_pct',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('critical_time_delta_pct',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('warning_time_delta_minutes',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('critical_time_delta_minutes',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('execution_plan', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('execution_reality', schema=None) as batch_op:
        batch_op.alter_column('tasks_json',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('materials_json',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('total_actual_time_minutes',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('inventory_materials', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('product_families', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_product_families_family_id'), type_='unique')

    with op.batch_alter_table('recurring_payments', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('periodicity',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('include_in_overhead',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('include_in_machine_cost',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=True)

    with op.batch_alter_table('workcenter_rates', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_workcenter_rates_code'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workcenter_rates', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_workcenter_rates_code'), ['code'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'missing_price'"),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'RON'"),
               existing_nullable=False)

    with op.batch_alter_table('recurring_payments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('include_in_machine_cost',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.alter_column('include_in_overhead',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'"),
               existing_nullable=False)
        batch_op.alter_column('periodicity',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'lunar'"),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'RON'"),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'alte_costuri'"),
               existing_nullable=False)

    with op.batch_alter_table('product_families', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_product_families_family_id'), ['family_id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(true)'),
               existing_nullable=False)

    with op.batch_alter_table('inventory_materials', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'"),
               existing_nullable=True)

    with op.batch_alter_table('execution_reality', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('total_actual_time_minutes',
               existing_type=sa.FLOAT(),
               server_default=sa.text('(0.0)'),
               existing_nullable=False)
        batch_op.alter_column('materials_json',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)
        batch_op.alter_column('tasks_json',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'[]'"),
               existing_nullable=False)

    with op.batch_alter_table('execution_plan', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)

    with op.batch_alter_table('execution_observation_config', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(true)'),
               existing_nullable=False)
        batch_op.alter_column('critical_time_delta_minutes',
               existing_type=sa.FLOAT(),
               server_default=sa.text('(120.0)'),
               existing_nullable=False)
        batch_op.alter_column('warning_time_delta_minutes',
               existing_type=sa.FLOAT(),
               server_default=sa.text('(30.0)'),
               existing_nullable=False)
        batch_op.alter_column('critical_time_delta_pct',
               existing_type=sa.FLOAT(),
               server_default=sa.text('(35.0)'),
               existing_nullable=False)
        batch_op.alter_column('warning_time_delta_pct',
               existing_type=sa.FLOAT(),
               server_default=sa.text('(15.0)'),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('employee_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'productive'"),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'"),
               existing_nullable=False)

    with op.batch_alter_table('cost_engine_config', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)
        batch_op.alter_column('allow_manual_override',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('(false)'),
               existing_nullable=False)
        batch_op.alter_column('metoda_overhead',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pe_ora_productiva'"),
               existing_nullable=False)
        batch_op.alter_column('overhead_profile_name',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'default'"),
               existing_nullable=False)
        batch_op.alter_column('moneda_implicita',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'RON'"),
               existing_nullable=False)

    # ### end Alembic commands ###