"""WorkOS Truth Metadata Contract — enums (W0-B1).

Projection metadata only. Not a parallel source of truth.
Canonical documentation remains in Git.
"""

from __future__ import annotations

from core.enums import AutoStrEnum

TRUTH_METADATA_VERSION = "workos_truth_metadata/v1"

# Authority ranks at or above this are reserved for canonical architecture / owner decisions.
CANONICAL_AUTHORITY_RANK_FLOOR = 100
# Runtime evidence must stay below this (never "canonical architecture" rank).
RUNTIME_AUTHORITY_RANK_CEILING = 49


class SubjectType(AutoStrEnum):
    SYSTEM = "SYSTEM"
    PAGE = "PAGE"
    ROUTE = "ROUTE"
    CONTRACT = "CONTRACT"
    DOCUMENT = "DOCUMENT"
    FLOW = "FLOW"
    RULE = "RULE"
    OWNER_DECISION = "OWNER_DECISION"
    STATUS = "STATUS"
    BOUNDARY = "BOUNDARY"
    HANDOFF = "HANDOFF"
    TERMINOLOGY = "TERMINOLOGY"
    FIGMA_NODE = "FIGMA_NODE"
    RUNTIME_CHECK = "RUNTIME_CHECK"


class ClaimType(AutoStrEnum):
    OWNS = "OWNS"
    READS = "READS"
    WRITES = "WRITES"
    HANDOFF = "HANDOFF"
    FORBIDDEN = "FORBIDDEN"
    FREEZE = "FREEZE"
    BOUNDARY = "BOUNDARY"
    STATUS = "STATUS"
    AUTHORITY = "AUTHORITY"
    TERMINOLOGY = "TERMINOLOGY"
    RUNTIME_BEHAVIOR = "RUNTIME_BEHAVIOR"
    DOCUMENT_STATUS = "DOCUMENT_STATUS"
    FIGMA_MAPPING = "FIGMA_MAPPING"


class AuthorityType(AutoStrEnum):
    OWNER_DECISION = "OWNER_DECISION"
    CANONICAL_ARCHITECTURE = "CANONICAL_ARCHITECTURE"
    CODE_CONTRACT = "CODE_CONTRACT"
    PERSISTENCE_CONTRACT = "PERSISTENCE_CONTRACT"
    FIGMA_APPROVED = "FIGMA_APPROVED"
    RUNTIME_EVIDENCE = "RUNTIME_EVIDENCE"
    TEST_EVIDENCE = "TEST_EVIDENCE"
    RECENT_WORKLOG = "RECENT_WORKLOG"
    SUPPORTING_DOCUMENT = "SUPPORTING_DOCUMENT"
    REFERENCE_ONLY = "REFERENCE_ONLY"


class ClaimStatus(AutoStrEnum):
    CURRENT = "CURRENT"
    CURRENT_WITH_GUARDS = "CURRENT_WITH_GUARDS"
    PARTIAL = "PARTIAL"
    PROPOSED = "PROPOSED"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"
    CONTRADICTORY = "CONTRADICTORY"
    OWNER_REVIEW_REQUIRED = "OWNER_REVIEW_REQUIRED"
    UNKNOWN = "UNKNOWN"


class DriftStatus(AutoStrEnum):
    ALIGNED = "ALIGNED"
    CODE_DRIFT = "CODE_DRIFT"
    RUNTIME_DRIFT = "RUNTIME_DRIFT"
    FIGMA_DRIFT = "FIGMA_DRIFT"
    DOCUMENTATION_DRIFT = "DOCUMENTATION_DRIFT"
    TERMINOLOGY_DRIFT = "TERMINOLOGY_DRIFT"
    MULTI_SOURCE_CONFLICT = "MULTI_SOURCE_CONFLICT"
    NOT_VALIDATED = "NOT_VALIDATED"


class VisibilityClass(AutoStrEnum):
    OPERATOR_SAFE = "OPERATOR_SAFE"
    ADMIN_ONLY = "ADMIN_ONLY"
    OWNER_ONLY = "OWNER_ONLY"
    INTERNAL_TECHNICAL = "INTERNAL_TECHNICAL"
    RESTRICTED = "RESTRICTED"
    HIDDEN_FROM_UI = "HIDDEN_FROM_UI"


class EvidenceType(AutoStrEnum):
    DOCUMENT = "DOCUMENT"
    CODE = "CODE"
    TEST = "TEST"
    RUNTIME = "RUNTIME"
    API = "API"
    DB = "DB"
    FIGMA = "FIGMA"
    QA = "QA"
    SCREENSHOT = "SCREENSHOT"
    WORKLOG = "WORKLOG"
    COMMIT = "COMMIT"


class OwnerType(AutoStrEnum):
    OWNER = "OWNER"
    SYSTEM_OWNER = "SYSTEM_OWNER"
    DOC_OWNER = "DOC_OWNER"
    UNASSIGNED = "UNASSIGNED"


class EdgeRelationshipType(AutoStrEnum):
    DIRECT = "DIRECT"
    INDIRECT = "INDIRECT"
    RESOURCE_PROVIDER = "RESOURCE_PROVIDER"
    TECHNICAL_CONSUMER = "TECHNICAL_CONSUMER"
    COMMERCIAL_CONSUMER = "COMMERCIAL_CONSUMER"
    FROZEN_DOWNSTREAM = "FROZEN_DOWNSTREAM"
    OPERATIONAL_CONSUMER = "OPERATIONAL_CONSUMER"
    BOUNDARY_ONLY = "BOUNDARY_ONLY"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    NO_CURRENT_LINK = "NO_CURRENT_LINK"


class FigmaFlowStatus(AutoStrEnum):
    APPROVED = "APPROVED"
    APPROVED_WITH_NOTES = "APPROVED_WITH_NOTES"
    PARTIAL = "PARTIAL"
    PROPOSED = "PROPOSED"
    EXPLORATORY = "EXPLORATORY"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    NOT_FOUND = "NOT_FOUND"


class FigmaApprovalStatus(AutoStrEnum):
    APPROVED = "APPROVED"
    APPROVED_WITH_NOTES = "APPROVED_WITH_NOTES"
    PARTIAL = "PARTIAL"
    PROPOSED = "PROPOSED"
    EXPLORATORY = "EXPLORATORY"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    NOT_FOUND = "NOT_FOUND"
    UNKNOWN = "UNKNOWN"


class FigmaDriftType(AutoStrEnum):
    NONE = "NONE"
    RUNTIME = "RUNTIME"
    DOCUMENTATION = "DOCUMENTATION"
    ACCEPTED_DEVIATION = "ACCEPTED_DEVIATION"
    MISSING_FLOW = "MISSING_FLOW"
    SUPERSEDED_FRAME = "SUPERSEDED_FRAME"


class DocumentAuthority(AutoStrEnum):
    CANONICAL_CURRENT = "CANONICAL_CURRENT"
    SUPPORTING_CURRENT = "SUPPORTING_CURRENT"
    RECENT_EVIDENCE = "RECENT_EVIDENCE"
    DIRECTION_ONLY = "DIRECTION_ONLY"
    REFERENCE = "REFERENCE"
    STALE = "STALE"
    SUPERSEDED = "SUPERSEDED"
    CONTRADICTORY = "CONTRADICTORY"
    OWNER_REVIEW_REQUIRED = "OWNER_REVIEW_REQUIRED"
    TEST_FIXTURE = "TEST_FIXTURE"


class DocumentCategory(AutoStrEnum):
    ARCHITECTURE = "ARCHITECTURE"
    SYSTEMS = "SYSTEMS"
    PAGES = "PAGES"
    CONTRACTS = "CONTRACTS"
    FIGMA = "FIGMA"
    ROADMAP = "ROADMAP"
    OWNER_DECISIONS = "OWNER_DECISIONS"
    UI_UX = "UI_UX"
    TERMINOLOGY = "TERMINOLOGY"
    QA = "QA"
    WORKLOG = "WORKLOG"
    RUNTIME_EVIDENCE = "RUNTIME_EVIDENCE"
    ARCHIVE_REFERENCE = "ARCHIVE_REFERENCE"
    PLAN = "PLAN"


class PageRole(AutoStrEnum):
    ENTRY_POINT = "ENTRY_POINT"
    OPERATIONAL_EDITOR = "OPERATIONAL_EDITOR"
    CATALOG = "CATALOG"
    ADMIN = "ADMIN"
    VIEWER = "VIEWER"
    DOWNSTREAM_CONSUMER = "DOWNSTREAM_CONSUMER"
    TECHNICAL_INSPECTOR = "TECHNICAL_INSPECTOR"
    DIAGNOSTIC = "DIAGNOSTIC"
    PREVIEW = "PREVIEW"
    REFERENCE = "REFERENCE"
    GOVERNANCE = "GOVERNANCE"
    LEGACY = "LEGACY"
    HIDDEN = "HIDDEN"
    DEAD_CANDIDATE = "DEAD_CANDIDATE"


# Authority types that require an assigned owner (not UNASSIGNED) for CURRENT* claims.
CANONICAL_AUTHORITY_TYPES: frozenset[AuthorityType] = frozenset(
    {
        AuthorityType.OWNER_DECISION,
        AuthorityType.CANONICAL_ARCHITECTURE,
        AuthorityType.CODE_CONTRACT,
        AuthorityType.PERSISTENCE_CONTRACT,
    }
)

FIGMA_APPROVED_STATUSES: frozenset[FigmaApprovalStatus] = frozenset(
    {
        FigmaApprovalStatus.APPROVED,
        FigmaApprovalStatus.APPROVED_WITH_NOTES,
    }
)
