import type { ColorRegistryItem } from "./colorRegistryTypes";

/** Oracal 8500 translucent catalogue (55 colors) — generated from ORAFOL sample colors */
export const ORACAL_8500_REGISTRY: ColorRegistryItem[] = [
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "010",
    name: "White",
    previewHex: "#E7E8E5",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "025",
    name: "Brimstone yellow",
    previewHex: "#D1C600",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "021",
    name: "Yellow",
    previewHex: "#FFCF00",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "013",
    name: "Zinc yellow",
    previewHex: "#F5BD00",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "020",
    name: "Golden yellow",
    previewHex: "#FBAA00",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "207",
    name: "Ochre yellow",
    previewHex: "#D2972F",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "015",
    name: "Yellow",
    previewHex: "#FEC500",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "034",
    name: "Orange",
    previewHex: "#E1512C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "330",
    name: "Fox red",
    previewHex: "#B0000D",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "323",
    name: "Coral red",
    previewHex: "#C91100",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "032",
    name: "Light red",
    previewHex: "#C91100",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "329",
    name: "Carnation red",
    previewHex: "#B0000D",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "016",
    name: "Crimson",
    previewHex: "#900E16",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "031",
    name: "Red",
    previewHex: "#B0000D",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "017",
    name: "Cherry red",
    previewHex: "#900E16",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "030",
    name: "Dark red",
    previewHex: "#900E16",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "085",
    name: "Pale pink",
    previewHex: "#ED84B6",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "413",
    name: "Light pink",
    previewHex: "#C22B6B",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "041",
    name: "Pink",
    previewHex: "#C22B6B",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "008",
    name: "Heather red",
    previewHex: "#900E16",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "040",
    name: "Violet",
    previewHex: "#5D2C68",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "403",
    name: "Light violet",
    previewHex: "#B893BC",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "012",
    name: "Lilac",
    previewHex: "#B893BC",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "527",
    name: "Pastel blue",
    previewHex: "#0089C3",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "053",
    name: "Light blue",
    previewHex: "#0089C3",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "052",
    name: "Azure blue",
    previewHex: "#005DAB",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "051",
    name: "Gentian blue",
    previewHex: "#004684",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "528",
    name: "Grey blue",
    previewHex: "#64788C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "005m",
    name: "Iddle blue",
    previewHex: "#0075BB",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "006",
    name: "Intensive blue",
    previewHex: "#1930AB",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "049",
    name: "King blue",
    previewHex: "#152A78",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "542",
    name: "Caribic blue",
    previewHex: "#0075BB",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "065",
    name: "Cobalt blue",
    previewHex: "#12226C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "007",
    name: "Dark blue",
    previewHex: "#1B2E5D",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "541",
    name: "Dark turquoise",
    previewHex: "#00818C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "066",
    name: "Turquoise blue",
    previewHex: "#009B97",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "054",
    name: "Turquoise",
    previewHex: "#009B97",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "062",
    name: "Light green",
    previewHex: "#00873C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "063",
    name: "Lime-tree green",
    previewHex: "#6AA72D",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "009m",
    name: "Iddle green",
    previewHex: "#00784B",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "614",
    name: "Reed green",
    previewHex: "#005236",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "068",
    name: "Grass green",
    previewHex: "#007A42",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "618",
    name: "Dragon green",
    previewHex: "#008164",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "087",
    name: "Emerald",
    previewHex: "#008164",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "060",
    name: "Dark green",
    previewHex: "#004028",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "070",
    name: "Black",
    previewHex: "#0D0E11",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "076",
    name: "Telegrey",
    previewHex: "#818689",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "072",
    name: "Light grey",
    previewHex: "#BFC2C0",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "074m",
    name: "Iddle grey",
    previewHex: "#8A8F8B",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "805",
    name: "Ivory",
    previewHex: "#F6F4EC",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "011",
    name: "Pale brown",
    previewHex: "#A8885C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "081",
    name: "Light brown",
    previewHex: "#A8885C",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "090",
    name: "Silver grey",
    previewHex: "#686A6D",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "091",
    name: "Gold",
    previewHex: "#756232",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "8500",
    code: "088",
    name: "Coffee brown",
    previewHex: "#432F1E",
    finish: "translucent_matte",
    usageScope: ["face_vinyl", "illuminated_face"],
    translucent: true,
    active: true,
    source: "ORAFOL ORACAL 8500 Translucent Cal",
    notes: "Translucent — color effect depends on LED behind face",
  },
];
