import type { ColorRegistryItem } from "./colorRegistryTypes";

/** Oracal 651 full catalogue (79 colors) — generated from ORAFOL sample colors */
export const ORACAL_651_REGISTRY: ColorRegistryItem[] = [
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "010",
    name: "White",
    previewHex: "#E6E9EE",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "010M",
    name: "White",
    previewHex: "#E6E9EE",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "020",
    name: "Golden yellow",
    previewHex: "#FBAA00",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "019",
    name: "Signal yellow",
    previewHex: "#E6A700",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "021",
    name: "Yellow",
    previewHex: "#FEC500",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "022",
    name: "Light yellow",
    previewHex: "#F2CA00",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "022M",
    name: "Light yellow",
    previewHex: "#F2CA00",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "025",
    name: "Brimstone yellow",
    previewHex: "#F2E210",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "026",
    name: "Purple red (gloss only",
    previewHex: "#5E050E",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "312",
    name: "Burgundy (gloss only",
    previewHex: "#6F000E",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "312M",
    name: "Burgundy",
    previewHex: "#6F000E",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "030",
    name: "Dark red",
    previewHex: "#900E16",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "031",
    name: "Red",
    previewHex: "#B0000D",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "031M",
    name: "Red",
    previewHex: "#B0000D",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "032",
    name: "Light red",
    previewHex: "#C91100",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "034",
    name: "Orange",
    previewHex: "#E1512C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "034M",
    name: "Orange",
    previewHex: "#E1512C",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "047",
    name: "Orange red",
    previewHex: "#D33100",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "036",
    name: "Light orange",
    previewHex: "#EA6700",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "035",
    name: "Pastel orange",
    previewHex: "#FC6C00",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "341",
    name: "Coral",
    previewHex: "#F88873",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "404",
    name: "Purple",
    previewHex: "#412773",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "040",
    name: "Violet",
    previewHex: "#5D2C68",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "040M",
    name: "Violet",
    previewHex: "#5D2C68",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "043",
    name: "Lavender",
    previewHex: "#775EA0",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "042",
    name: "Lilac",
    previewHex: "#B893BC",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "041",
    name: "Pink",
    previewHex: "#C22B6B",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "041M",
    name: "Pink",
    previewHex: "#C22B6B",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "045",
    name: "Soft pink",
    previewHex: "#ED84B6",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "045M",
    name: "Soft pink",
    previewHex: "#ED84B6",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "562",
    name: "Deep sea blue",
    previewHex: "#131E3A",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "518",
    name: "Steel blue",
    previewHex: "#13133E",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "050",
    name: "Dark blue",
    previewHex: "#1B2E5D",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "050M",
    name: "Dark blue",
    previewHex: "#1B2E5D",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "065",
    name: "Cobalt blue",
    previewHex: "#12226C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "049",
    name: "King blue",
    previewHex: "#152A78",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "086",
    name: "Brilliant blue",
    previewHex: "#1930AB",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "067",
    name: "Blue",
    previewHex: "#003A79",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "057",
    name: "Traffic blue",
    previewHex: "#00408C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "051",
    name: "Gentian blue",
    previewHex: "#004684",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "098",
    name: "Gentian",
    previewHex: "#0050A2",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "052",
    name: "Azure blue",
    previewHex: "#005DAB",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "084",
    name: "Sky blue",
    previewHex: "#0075BB",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "084M",
    name: "Sky blue",
    previewHex: "#0075BB",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "053",
    name: "Light blue",
    previewHex: "#0089C3",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "056",
    name: "Ice blue",
    previewHex: "#3DA1D2",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "066",
    name: "Turquoise blue",
    previewHex: "#00818C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "054",
    name: "Turquoise",
    previewHex: "#009B97",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "054M",
    name: "Turquoise",
    previewHex: "#009B97",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "055m",
    name: "Int",
    previewHex: "#5FCDB7",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "060",
    name: "Dark green",
    previewHex: "#004028",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "613",
    name: "Forest green",
    previewHex: "#005236",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "061",
    name: "Green",
    previewHex: "#00784B",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "061M",
    name: "Green",
    previewHex: "#00784B",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "068",
    name: "Grass green",
    previewHex: "#007A42",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "062",
    name: "Light green",
    previewHex: "#00873C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "064",
    name: "Yellow green",
    previewHex: "#289901",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "063",
    name: "Lime-tree green",
    previewHex: "#6AA72D",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "080",
    name: "Brown",
    previewHex: "#432F1E",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "080M",
    name: "Brown",
    previewHex: "#432F1E",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "083",
    name: "Nut brown",
    previewHex: "#AF591F",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "824",
    name: "Imitation gold",
    previewHex: "#D2972F",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "081",
    name: "Light brown",
    previewHex: "#A8885C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "082",
    name: "Beige",
    previewHex: "#CEC09F",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "023",
    name: "Cream (gloss only",
    previewHex: "#EBD494",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "070",
    name: "Black",
    previewHex: "#0D0E11",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "070M",
    name: "Black",
    previewHex: "#231F20",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "073",
    name: "Dark grey",
    previewHex: "#4B4C4C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "073M",
    name: "Dark grey",
    previewHex: "#4B4C4C",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "071",
    name: "Grey",
    previewHex: "#757D7C",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "071M",
    name: "Grey",
    previewHex: "#757D7C",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "076",
    name: "Telegrey",
    previewHex: "#818689",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "074m",
    name: "Iddle grey",
    previewHex: "#8A8F8B",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "072",
    name: "Light grey",
    previewHex: "#BFC2C0",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "090",
    name: "Silver grey",
    previewHex: "#686A6D",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "090M",
    name: "Silver grey metallic",
    previewHex: "#686A6D",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "091",
    name: "Gold",
    previewHex: "#756232",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "091M",
    name: "Gold metallic",
    previewHex: "#756232",
    finish: "matte",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Matte variant",
  },
  {
    system: "ORACAL",
    brand: "Oracal",
    series: "651",
    code: "092",
    name: "Copper",
    previewHex: "#6B411D",
    finish: "gloss",
    usageScope: ["return", "face_vinyl"],
    translucent: false,
    active: true,
    source: "ORAFOL ORACAL 651 Intermediate Cal",
    notes: "Colored cast vinyl",
  },
];
