import type { ColorRegistryItem } from "./colorRegistryTypes";

/** RAL Classic full palette (213 colors) — generated from import/sources/ral_standard.csv */
export const RAL_COLOR_REGISTRY: ColorRegistryItem[] = [
  {
    system: "RAL",
    code: "1000",
    name: "Green beige",
    previewHex: "#BEBD7F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1001",
    name: "Beige",
    previewHex: "#C2B078",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1002",
    name: "Sand yellow",
    previewHex: "#C6A664",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1003",
    name: "Signal yellow",
    previewHex: "#E5BE01",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1004",
    name: "Golden yellow",
    previewHex: "#CDA434",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1005",
    name: "Honey yellow",
    previewHex: "#A98307",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1006",
    name: "Maize yellow",
    previewHex: "#E4A010",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1007",
    name: "Daffodil yellow",
    previewHex: "#DC9D00",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1011",
    name: "Brown beige",
    previewHex: "#8A6642",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1012",
    name: "Lemon yellow",
    previewHex: "#C7B446",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1013",
    name: "Oyster white",
    previewHex: "#EAE6CA",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1014",
    name: "Ivory",
    previewHex: "#E1CC4F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1015",
    name: "Light ivory",
    previewHex: "#E6D690",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1016",
    name: "Sulfur yellow",
    previewHex: "#EDFF21",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1017",
    name: "Saffron yellow",
    previewHex: "#F5D033",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1018",
    name: "Zinc yellow",
    previewHex: "#F8F32B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1019",
    name: "Grey beige",
    previewHex: "#9E9764",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1020",
    name: "Olive yellow",
    previewHex: "#999950",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1021",
    name: "Rape yellow",
    previewHex: "#F3DA0B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1023",
    name: "Traffic yellow",
    previewHex: "#FAD201",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1024",
    name: "Ochre yellow",
    previewHex: "#AEA04B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1026",
    name: "Luminous yellow",
    previewHex: "#FFFF00",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1027",
    name: "Curry",
    previewHex: "#9D9101",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1028",
    name: "Melon yellow",
    previewHex: "#F4A900",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1032",
    name: "Broom yellow",
    previewHex: "#D6AE01",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1033",
    name: "Dahlia yellow",
    previewHex: "#F3A505",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1034",
    name: "Pastel yellow",
    previewHex: "#EFA94A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1035",
    name: "Pearl beige",
    previewHex: "#6A5D4D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1036",
    name: "Pearl gold",
    previewHex: "#705335",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "1037",
    name: "Sun yellow",
    previewHex: "#F39F18",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2000",
    name: "Yellow orange",
    previewHex: "#ED760E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2001",
    name: "Red orange",
    previewHex: "#C93C20",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2002",
    name: "Vermilion",
    previewHex: "#CB2821",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2003",
    name: "Pastel orange",
    previewHex: "#FF7514",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2004",
    name: "Pure orange",
    previewHex: "#F44611",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2005",
    name: "Luminous orange",
    previewHex: "#FF2301",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2007",
    name: "Luminous bright orange",
    previewHex: "#FFA420",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2008",
    name: "Bright red orange",
    previewHex: "#F75E25",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2009",
    name: "Traffic orange",
    previewHex: "#F54021",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2010",
    name: "Signal orange",
    previewHex: "#D84B20",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2011",
    name: "Deep orange",
    previewHex: "#EC7C26",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2012",
    name: "Salmon range",
    previewHex: "#E55137",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "2013",
    name: "Pearl orange",
    previewHex: "#C35831",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3000",
    name: "Flame red",
    previewHex: "#AF2B1E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3001",
    name: "Signal red",
    previewHex: "#A52019",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3002",
    name: "Carmine red",
    previewHex: "#A2231D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3003",
    name: "Ruby red",
    previewHex: "#9B111E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3004",
    name: "Purple red",
    previewHex: "#75151E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3005",
    name: "Wine red",
    previewHex: "#5E2129",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3007",
    name: "Black red",
    previewHex: "#412227",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3009",
    name: "Oxide red",
    previewHex: "#642424",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3011",
    name: "Brown red",
    previewHex: "#781F19",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3012",
    name: "Beige red",
    previewHex: "#C1876B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3013",
    name: "Tomato red",
    previewHex: "#A12312",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3014",
    name: "Antique pink",
    previewHex: "#D36E70",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3015",
    name: "Light pink",
    previewHex: "#EA899A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3016",
    name: "Coral red",
    previewHex: "#B32821",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3017",
    name: "Rose",
    previewHex: "#E63244",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3018",
    name: "Strawberry red",
    previewHex: "#D53032",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3020",
    name: "Traffic red",
    previewHex: "#CC0605",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3022",
    name: "Salmon pink",
    previewHex: "#D95030",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3024",
    name: "Luminous red",
    previewHex: "#F80000",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3026",
    name: "Luminous bright red",
    previewHex: "#FE0000",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3027",
    name: "Raspberry red",
    previewHex: "#C51D34",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3028",
    name: "Pure  red",
    previewHex: "#CB3234",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3031",
    name: "Orient red",
    previewHex: "#B32428",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3032",
    name: "Pearl ruby red",
    previewHex: "#721422",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "3033",
    name: "Pearl pink",
    previewHex: "#B44C43",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4001",
    name: "Red lilac",
    previewHex: "#6D3F5B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4002",
    name: "Red violet",
    previewHex: "#922B3E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4003",
    name: "Heather violet",
    previewHex: "#DE4C8A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4004",
    name: "Claret violet",
    previewHex: "#641C34",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4005",
    name: "Blue lilac",
    previewHex: "#6C4675",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4006",
    name: "Traffic purple",
    previewHex: "#A03472",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4007",
    name: "Purple violet",
    previewHex: "#4A192C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4008",
    name: "Signal violet",
    previewHex: "#924E7D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4009",
    name: "Pastel violet",
    previewHex: "#A18594",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4010",
    name: "Telemagenta",
    previewHex: "#CF3476",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4011",
    name: "Pearl violet",
    previewHex: "#8673A1",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "4012",
    name: "Pearl black berry",
    previewHex: "#6C6874",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5000",
    name: "Violet blue",
    previewHex: "#354D73",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5001",
    name: "Green blue",
    previewHex: "#1F3438",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5002",
    name: "Ultramarine blue",
    previewHex: "#20214F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5003",
    name: "Saphire blue",
    previewHex: "#1D1E33",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5004",
    name: "Black blue",
    previewHex: "#18171C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5005",
    name: "Signal blue",
    previewHex: "#1E2460",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5007",
    name: "Brillant blue",
    previewHex: "#3E5F8A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5008",
    name: "Grey blue",
    previewHex: "#26252D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5009",
    name: "Azure blue",
    previewHex: "#025669",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5010",
    name: "Gentian blue",
    previewHex: "#0E294B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5011",
    name: "Steel blue",
    previewHex: "#231A24",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5012",
    name: "Light blue",
    previewHex: "#3B83BD",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5013",
    name: "Cobalt blue",
    previewHex: "#1E213D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5014",
    name: "Pigeon blue",
    previewHex: "#606E8C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5015",
    name: "Sky blue",
    previewHex: "#2271B3",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5017",
    name: "Traffic blue",
    previewHex: "#063971",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5018",
    name: "Turquoise blue",
    previewHex: "#3F888F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5019",
    name: "Capri blue",
    previewHex: "#1B5583",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5020",
    name: "Ocean blue",
    previewHex: "#1D334A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5021",
    name: "Water blue",
    previewHex: "#256D7B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5022",
    name: "Night blue",
    previewHex: "#252850",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5023",
    name: "Distant blue",
    previewHex: "#49678D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5024",
    name: "Pastel blue",
    previewHex: "#5D9B9B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5025",
    name: "Pearl gentian blue",
    previewHex: "#2A6478",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "5026",
    name: "Pearl night blue",
    previewHex: "#102C54",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6000",
    name: "Patina green",
    previewHex: "#316650",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6001",
    name: "Emerald green",
    previewHex: "#287233",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6002",
    name: "Leaf green",
    previewHex: "#2D572C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6003",
    name: "Olive green",
    previewHex: "#424632",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6004",
    name: "Blue green",
    previewHex: "#1F3A3D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6005",
    name: "Moss green",
    previewHex: "#2F4538",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6006",
    name: "Grey olive",
    previewHex: "#3E3B32",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6007",
    name: "Bottle green",
    previewHex: "#343B29",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6008",
    name: "Brown green",
    previewHex: "#39352A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6009",
    name: "Fir green",
    previewHex: "#31372B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6010",
    name: "Grass green",
    previewHex: "#35682D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6011",
    name: "Reseda green",
    previewHex: "#587246",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6012",
    name: "Black green",
    previewHex: "#343E40",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6013",
    name: "Reed green",
    previewHex: "#6C7156",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6014",
    name: "Yellow olive",
    previewHex: "#47402E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6015",
    name: "Black olive",
    previewHex: "#3B3C36",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6016",
    name: "Turquoise green",
    previewHex: "#1E5945",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6017",
    name: "May green",
    previewHex: "#4C9141",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6018",
    name: "Yellow green",
    previewHex: "#57A639",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6019",
    name: "Pastel green",
    previewHex: "#BDECB6",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6020",
    name: "Chrome green",
    previewHex: "#2E3A23",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6021",
    name: "Pale green",
    previewHex: "#89AC76",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6022",
    name: "Olive drab",
    previewHex: "#25221B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6024",
    name: "Traffic green",
    previewHex: "#308446",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6025",
    name: "Fern green",
    previewHex: "#3D642D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6026",
    name: "Opal green",
    previewHex: "#015D52",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6027",
    name: "Light green",
    previewHex: "#84C3BE",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6028",
    name: "Pine green",
    previewHex: "#2C5545",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6029",
    name: "Mint green",
    previewHex: "#20603D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6032",
    name: "Signal green",
    previewHex: "#317F43",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6033",
    name: "Mint turquoise",
    previewHex: "#497E76",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6034",
    name: "Pastel turquoise",
    previewHex: "#7FB5B5",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6035",
    name: "Pearl green",
    previewHex: "#1C542D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6036",
    name: "Pearl opal green",
    previewHex: "#193737",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6037",
    name: "Pure green",
    previewHex: "#008F39",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "6038",
    name: "Luminous green",
    previewHex: "#00BB2D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7000",
    name: "Squirrel grey",
    previewHex: "#78858B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7001",
    name: "Silver grey",
    previewHex: "#8A9597",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7002",
    name: "Olive grey",
    previewHex: "#7E7B52",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7003",
    name: "Moss grey",
    previewHex: "#6C7059",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7004",
    name: "Signal grey",
    previewHex: "#969992",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7005",
    name: "Mouse grey",
    previewHex: "#646B63",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7006",
    name: "Beige grey",
    previewHex: "#6D6552",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7008",
    name: "Khaki grey",
    previewHex: "#6A5F31",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7009",
    name: "Green grey",
    previewHex: "#4D5645",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7010",
    name: "Tarpaulin grey",
    previewHex: "#4C514A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7011",
    name: "Iron grey",
    previewHex: "#434B4D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7012",
    name: "Basalt grey",
    previewHex: "#4E5754",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7013",
    name: "Brown grey",
    previewHex: "#464531",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7015",
    name: "Slate grey",
    previewHex: "#434750",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7016",
    name: "Anthracite grey",
    previewHex: "#293133",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7021",
    name: "Black grey",
    previewHex: "#23282B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7022",
    name: "Umbra grey",
    previewHex: "#332F2C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7023",
    name: "Concrete grey",
    previewHex: "#686C5E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7024",
    name: "Graphite grey",
    previewHex: "#474A51",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7026",
    name: "Granite grey",
    previewHex: "#2F353B",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7030",
    name: "Stone grey",
    previewHex: "#8B8C7A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7031",
    name: "Blue grey",
    previewHex: "#474B4E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7032",
    name: "Pebble grey",
    previewHex: "#B8B799",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7033",
    name: "Cement grey",
    previewHex: "#7D8471",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7034",
    name: "Yellow grey",
    previewHex: "#8F8B66",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7035",
    name: "Light grey",
    previewHex: "#D7D7D7",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7036",
    name: "Platinum grey",
    previewHex: "#7F7679",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7037",
    name: "Dusty grey",
    previewHex: "#7D7F7D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7038",
    name: "Agate grey",
    previewHex: "#B5B8B1",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7039",
    name: "Quartz grey",
    previewHex: "#6C6960",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7040",
    name: "Window grey",
    previewHex: "#9DA1AA",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7042",
    name: "Traffic grey A",
    previewHex: "#8D948D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7043",
    name: "Traffic grey B",
    previewHex: "#4E5452",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7044",
    name: "Silk grey",
    previewHex: "#CAC4B0",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7045",
    name: "Telegrey 1",
    previewHex: "#909090",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7046",
    name: "Telegrey 2",
    previewHex: "#82898F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7047",
    name: "Telegrey 4",
    previewHex: "#D0D0D0",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "7048",
    name: "Pearl mouse grey",
    previewHex: "#898176",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8000",
    name: "Green brown",
    previewHex: "#826C34",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8001",
    name: "Ochre brown",
    previewHex: "#955F20",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8002",
    name: "Signal brown",
    previewHex: "#6C3B2A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8003",
    name: "Clay brown",
    previewHex: "#734222",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8004",
    name: "Copper brown",
    previewHex: "#8E402A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8007",
    name: "Fawn brown",
    previewHex: "#59351F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8008",
    name: "Olive brown",
    previewHex: "#6F4F28",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8011",
    name: "Nut brown",
    previewHex: "#5B3A29",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8012",
    name: "Red brown",
    previewHex: "#592321",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8014",
    name: "Sepia brown",
    previewHex: "#382C1E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8015",
    name: "Chestnut brown",
    previewHex: "#633A34",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8016",
    name: "Mahogany brown",
    previewHex: "#4C2F27",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8017",
    name: "Chocolate brown",
    previewHex: "#45322E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8019",
    name: "Grey brown",
    previewHex: "#403A3A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8022",
    name: "Black brown",
    previewHex: "#212121",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8023",
    name: "Orange brown",
    previewHex: "#A65E2E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8024",
    name: "Beige brown",
    previewHex: "#79553D",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8025",
    name: "Pale brown",
    previewHex: "#755C48",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8028",
    name: "Terra brown",
    previewHex: "#4E3B31",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "8029",
    name: "Pearl copper",
    previewHex: "#763C28",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9001",
    name: "Cream",
    previewHex: "#FDF4E3",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9002",
    name: "Grey white",
    previewHex: "#E7EBDA",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9003",
    name: "Signal white",
    previewHex: "#F4F4F4",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9004",
    name: "Signal black",
    previewHex: "#282828",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9005",
    name: "Jet black",
    previewHex: "#0A0A0A",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9006",
    name: "White aluminium",
    previewHex: "#A5A5A5",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9007",
    name: "Grey aluminium",
    previewHex: "#8F8F8F",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9010",
    name: "Pure white",
    previewHex: "#FFFFFF",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9011",
    name: "Graphite black",
    previewHex: "#1C1C1C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9016",
    name: "Traffic white",
    previewHex: "#F6F6F6",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9017",
    name: "Traffic black",
    previewHex: "#1E1E1E",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9018",
    name: "Papyrus white",
    previewHex: "#D7D7D7",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9022",
    name: "Pearl light grey",
    previewHex: "#9C9C9C",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
  {
    system: "RAL",
    code: "9023",
    name: "Pearl dark grey",
    previewHex: "#828282",
    finish: "matte",
    usageScope: ["return", "structure", "cable_channel"],
    active: true,
    source: "RAL Classic (ral_standard.csv gist/nichtich)",
    notes: "Preview HEX approximate — physical RAL standard is authoritative",
  },
];
